[project]
name = "rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax==0.5.0",
    "jax-metal==0.1.1",
    "jaxlib==0.5.0",
]
